### ISSUE TITLE
siteflag

### ISSUE THREAD

**Issue by Nuvion** [kevprakash/R6-Match-Replay-Analysis#1]
![image](https://github.com/kevprakash/R6-Match-Replay-Analysis/assets/76669118/b9b5fc77-d1bb-4aa6-a145-e663111ee58a)
some issues with the siteflag is halting the program.

**Comment by kevprakash** [comment]
Pushed an update that should prevent this specific error from occurring. However, recording site/spawn does not work properly in certain cases. Will add as a bug to issues.
